### ISSUE TITLE
is the OCP types docs necessary here? seems redundant with the OCP types docs from open-connectome

### ISSUE THREAD

**Issue by jovo** [neurodata/ndtilecache#10]

**Comment by kunallillaney** [comment]
the ocp type docs is not but I will link them off to the ones in openconnectome. there are some parts of the documentation which are common and can live in open-connectome but API docs for API's in this repo should stay in this repo.

**Comment by jovo** [comment]
ok, makes sense to me. thanks.

**Comment by kunallillaney** [comment]
http://openconnectome.github.io/ocptilecache/api/tilecache_api.html
This is done.
