### ISSUE TITLE
uwsgi doesn't like two directories called ocptilecache

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndtilecache#6]
It doesn't seem to be able to differentiate between OCPTILECACHE and ocptilecache. But maybe there's a different issue. @kunallillaney do you have the kunal-devel branch deployed on uwsgi anywhere?

**Comment by alexbaden** [comment]
This may not be a problem, actually...

**Comment by kunallillaney** [comment]
I will look into it.

**Comment by alexbaden** [comment]
My mac doesn't seem to like it... I think we should change the directory names.

**Comment by kunallillaney** [comment]
Checking.

**Comment by kunallillaney** [comment]
this works on ubuntu. I just checked. I will deploy it on centos and check. This could be a mac specific problem. But we do not deplot uwsgi on mac. Both Randal and myself only use the dev server there.

**Comment by alexbaden** [comment]
I can't get the dev server to run on my mac:

```
ImportError: Could not import settings 'OCPTILECACHE.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named OCPTILECACHE.settings
```

**Comment by kunallillaney** [comment]
Okay. So this is an error in mac where it does differentiate between directory names in uppercase letters. Will change the name and push a new one.

**Comment by kunallillaney** [comment]
Pushed.
