### ISSUE TITLE
errors in new branch?

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndtilecache#7]
http://brainviz1.cs.jhu.edu/ocptilecache/tilecache/freeman14/image/xy/0/0_1_3.png

http://brainviz1.cs.jhu.edu/ocptilecache/tilecache/freeman14/image/xy/0/0/0_1_3.png

http://brainviz1.cs.jhu.edu/ocptilecache/tilecache/freeman14/image/xy/1/1/0_1_3.png

Any ideas?

**Comment by kunallillaney** [comment]
Timeseries might have some issues. I will fix it.

**Comment by kunallillaney** [comment]
Done.
